name: Multiple Builds
on:
  pull_request:
    branches:
      - master
jobs:
  build: 
    continue-on-error: true
    strategy:
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
            # Add a specific combination
          - node-version: 14
            os: ubuntu-latest
        exclude:
            # Exclude a specific combination
          - node-version: 16
            os: windows-latest
          
    runs-on: ${{ matrix.os }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix['node-version'] }}
        - name: Install dependencies
          run: npm ci
        - name: Build project
          run: npm run build
